---
  el:
    hosts:
      centos7:
        ansible_connection: docker
  deb:
    hosts:
      ubuntu:
        ansible_connection: docker
  prod:
    hosts:
      localhost:
        ansible_connection: local